import { type SchemaPairMap } from './types'
import { ASSET_MAP } from './asset'
import { GREEKS_MAP } from './greeks'

// Schema map for the 'TICKER' struct.
export const TICKER_MAP: SchemaPairMap = Object.freeze({
  FULL_TO_LITE: {
    event_time: 'et',
    asset: ['a', ASSET_MAP.FULL_TO_LITE],
    mark_price: 'mp',
    index_price: 'ip',
    last_price: 'lp',
    last_size: 'ls',
    mid_price: 'mp1',
    best_bid_price: 'bb',
    best_bid_size: 'bb1',
    best_bid_num_orders: 'bb2',
    best_ask_price: 'ba',
    best_ask_size: 'ba1',
    best_ask_num_orders: 'ba2',
    volume: 'v',
    volume_change: 'vc',
    quote_volume: 'qv',
    quote_volume_change: 'qv1',
    taker_buy_trades: 'tb',
    taker_buy_trades_change: 'tb1',
    maker_buy_trades: 'mb',
    maker_buy_trades_change: 'mb1',
    high_price: 'hp',
    low_price: 'lp1',
    current_funding_rate: 'cf',
    avg_funding_rate: 'af',
    open_interest: 'oi',
    num_trades: 'nt',
    num_trades_change: 'nt1',
    taker_buy_sell_ratio: 'tb2',
    taker_buy_sell_ratio_change: 'tb3',
    avg_price: 'ap',
    avg_price_change: 'ap1',
    avg_volume: 'av',
    avg_volume_change: 'av1',
    greeks: ['g', GREEKS_MAP.FULL_TO_LITE]
  },
  LITE_TO_FULL: {
    et: 'event_time',
    a: ['asset', ASSET_MAP.LITE_TO_FULL],
    mp: 'mark_price',
    ip: 'index_price',
    lp: 'last_price',
    ls: 'last_size',
    mp1: 'mid_price',
    bb: 'best_bid_price',
    bb1: 'best_bid_size',
    bb2: 'best_bid_num_orders',
    ba: 'best_ask_price',
    ba1: 'best_ask_size',
    ba2: 'best_ask_num_orders',
    v: 'volume',
    vc: 'volume_change',
    qv: 'quote_volume',
    qv1: 'quote_volume_change',
    tb: 'taker_buy_trades',
    tb1: 'taker_buy_trades_change',
    mb: 'maker_buy_trades',
    mb1: 'maker_buy_trades_change',
    hp: 'high_price',
    lp1: 'low_price',
    cf: 'current_funding_rate',
    af: 'avg_funding_rate',
    oi: 'open_interest',
    nt: 'num_trades',
    nt1: 'num_trades_change',
    tb2: 'taker_buy_sell_ratio',
    tb3: 'taker_buy_sell_ratio_change',
    ap: 'avg_price',
    ap1: 'avg_price_change',
    av: 'avg_volume',
    av1: 'avg_volume_change',
    g: ['greeks', GREEKS_MAP.LITE_TO_FULL]
  }
})
