name: Check

on:
  workflow_dispatch:
  # Run CI/CD jobs on pull request
  pull_request:
    paths:
      # only run jobs when source files are changed
      - src/**
      # or when this workflow file is changed
      - .github/workflows/check.yml
      # Add all monorepo dependency folders

jobs:
  ts-bot-check:
    runs-on: ubuntu-latest
    env:
      node: ">=20"
      module: "./frontend/ts-bot"
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node }}
          cache: "yarn"
          cache-dependency-path: ${{ env.module }}/yarn.lock
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: |
          cd ${{ env.module }}
          yarn install --frozen-lockfile

      # Ensure the files are linted before they are pushed
      - name: Npm Lint
        run: |
          cd ${{ env.module }}
          npm run lint --fix
          $GITHUB_WORKSPACE/.github/scripts/assert_no_files_changed.sh

      # Ensure build not broken
      - name: Npm run build
        run: |
          cd ${{ env.module }}
          npm run build
