name: Publish
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release.yaml
      - src/**

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      node: '20.9.0'
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: ${{ env.node }}
            registry-url: https://registry.npmjs.org
            cache: npm
            cache-dependency-path: package-lock.json

        - name: get-npm-version
          id: tag-version
          uses: martinbeentjes/npm-get-version-action@v1.3.1
          with:
            path: frontend/market

        - name: Push tag
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            tag_prefix: frontend/market/v
            custom_tag: ${{ steps.tag-version.outputs.current-version }}
            fetch_all_tags: true

        - run: npm ci
        - run: npm config set _authToken=${{ secrets.NPM_PUBLISH_TOKEN }}
        - run: npm run release
